apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: stock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: ccteam4acr.azurecr.io/stock
          ports:
            - containerPort: 8080